// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvbscdmnsrxxefijlbyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2YnNjZG1uc3J4eGVmaWpsYnl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzY1OTMsImV4cCI6MjA3MDgxMjU5M30.oM83ycJHSlf4lTUQcwRVhGhMcxNqlLHvCgYgGArR91Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});